#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

SRC=/usr/local/src

# appengine sdk
VERSION="google_appengine_1.7.5.zip"
SHA1SUM="f7d503c4b1c18112595cf815bfac9afa08601422"

dl http://googleappengine.googlecode.com/files/${VERSION} $SRC

echo "$SHA1SUM  $VERSION" > $SRC/$VERSION.sha1
cd $SRC; sha1sum -c $VERSION.sha1; rm $VERSION.sha1; cd -


