#!/bin/sh -ex

SRC=/usr/local/src
GAE_PYTHON=/var/www/google_appengine

# unpack google appengine
NAME=google_appengine
unzip -q $SRC/${NAME}_*.zip -d $SRC
rm $SRC/${NAME}_*.zip
mv -T $SRC/$NAME $GAE_PYTHON
chown -R root:root $GAE_PYTHON

# setup cgi template
mv $GAE_PYTHON/new_project_template $GAE_PYTHON/template-cgi

# setup webapp templates
mv $SRC/template-webapp $GAE_PYTHON/template-webapp

# setup django template
TEMPLATE=$GAE_PYTHON/template-django
mv $SRC/django-testapp $TEMPLATE
rm -rf $TEMPLATE/.git
ln -s $SRC/django-nonrel/django $TEMPLATE/django
ln -s $SRC/django-autoload/autoload $TEMPLATE/autoload
ln -s $SRC/django-dbindexer/dbindexer $TEMPLATE/dbindexer
ln -s $SRC/djangoappengine/djangoappengine $TEMPLATE/djangoappengine
ln -s $SRC/djangotoolbox/djangotoolbox $TEMPLATE/djangotoolbox

# add sdk to path (required for django template)
cat > /root/.bashrc.d/google_appengine <<EOF
# required for google appengine (django)
if \$(echo \$PATH | grep -q -v $GAE_PYTHON); then
    PATH="\$PATH:$GAE_PYTHON"
fi
EOF
chmod +x /root/.bashrc.d/google_appengine

# tweak tkl-webcp
sed -i "s|width: 520px;|width: 580px;|" /var/www/css/base.css

