#!/bin/sh -ex

SRC=/usr/local/src
GAE_PYTHON=/var/www/google_appengine

# unpack google appengine
NAME=google_appengine
unzip -q $SRC/${NAME}_*.zip -d $SRC
rm $SRC/${NAME}_*.zip
mv -T $SRC/$NAME $GAE_PYTHON
chown -R root:root $GAE_PYTHON

# setup cgi template
mv $GAE_PYTHON/new_project_template $GAE_PYTHON/template-cgi

# setup webapp templates
mv $SRC/template-webapp $GAE_PYTHON/template-webapp

# setup django template: http://www.allbuttonspressed.com/projects/djangoappengine
TEMPLATE=$GAE_PYTHON/template-django
git clone https://github.com/django-nonrel/django-testapp.git $TEMPLATE
rm -rf $TEMPLATE/.git
cd $TEMPLATE

mkdir -p build
pip install --download='./build' --no-install -r requirements.txt
unzip -q build/django-autoload-*.zip -d build
unzip -q build/django-dbindexer-*.zip -d build
unzip -q build/django-nonrel-*.zip -d build
unzip -q build/djangoappengine-*.zip -d build
unzip -q build/djangotoolbox-*.zip -d build
cp -r build/django-autoload/autoload ./autoload
cp -r build/django-dbindexer/dbindexer ./dbindexer
cp -r build/django-nonrel/django ./django
cp -r build/djangoappengine/djangoappengine ./djangoappengine
cp -r build/djangotoolbox/djangotoolbox ./djangotoolbox
rm -rf ./djangoappengine/djangoappengine.egg-info

# add sdk to path (required for django template)
cat > /root/.bashrc.d/google_appengine <<EOF
# required for google appengine (django)
if \$(echo \$PATH | grep -q -v $GAE_PYTHON); then
    PATH="\$PATH:$GAE_PYTHON"
fi
EOF
chmod +x /root/.bashrc.d/google_appengine

# tweak tkl-webcp
sed -i "s|width: 520px;|width: 580px;|" /var/www/css/base.css

