#!/bin/bash -e
# regenerate django secret key

. /etc/default/inithooks

CONF=/var/www/google_appengine/template-django/settings.py
sed -i "s|^SECRET_KEY = \(.*\)|SECRET_KEY = \'$(mcookie)$(mcookie)\'|" $CONF

